### ISSUE TITLE
Add prefix-postfix conversion

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/notation-converter#26]
## 🚀 Feature

The project already has infix-prefix (& vice-versa) and infix-postfix (& vice-versa) conversion. Please add prefix-postfix conversion.

## Please Describe The Problem To Be Solved

Investigate the current project code, feel free to try some conversions and know-how data structures such as [Stack](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)) are used for the conversion. Design and implement prefix-postfix code accordingly.

**Comment by lokesh-0706** [comment]
@adityabisoi Can you please assign this to me?

**Comment by ShrutiVaishnav28** [comment]
@adityabisoi can you pls assign this project to me?

**Comment by Shweta597** [comment]
@adityabisoi I would like to work on this issue under GSSOC'22

**Comment by adityabisoi** [comment]
@ShrutiVaishnav28 Please make a PR within tonight. @Shweta597 I'll assign you the issue if @ShrutiVaishnav28 doesn't make a PR by tonight.

**Comment by Shweta597** [comment]
@adityabisoi Can you now assign me the issue please

**Comment by adityabisoi** [comment]
Assigning the issue to @Shweta597
