### ISSUE TITLE
Add postfix-prefix conversion

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/notation-converter#27]
## 🚀 Feature

The project already has infix-prefix (& vice-versa) and infix-postfix (& vice-versa) conversion. Please add postfix-prefix conversion.

## Please Describe The Problem To Be Solved

Investigate the current project code, feel free to try some conversions and know-how data structures such as [Stack](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)) are used for the conversion. Design and implement postfix-prefix code accordingly.

**Comment by siddiq-1018** [comment]
@adityabisoi can you please assign it to me?

**Comment by bharat1999** [comment]
Can I work on this under GSSOC 22

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by bharat1999** [comment]
Abhilasha I am working on it

**Comment by Shweta597** [comment]
I want to work on this Issue under GSSOC'22

**Comment by adityabisoi** [comment]
@bharat1999 Its already been 7 days. Please make a PR by tonight.

**Comment by Shweta597** [comment]
@adityabisoi now can you assign me this issue please

**Comment by adityabisoi** [comment]
@Shweta597 One issue at a time.

**Comment by Shweta597** [comment]
@adityabisoi I have already created the pull request for the previous issue now I am not working on any issue

**Comment by adityabisoi** [comment]
Since @Abhilasha-Jairath commented second, @Abhilasha-Jairath do you still want to work on this?

**Comment by vai-shali** [comment]
Hi, if no one is working on this, could I work on this issue for GSSOC'22?

**Comment by adityabisoi** [comment]
@Shweta597 Had commented next, do you want to take it?

**Comment by Shweta597** [comment]
Yes I want to work on this

**Comment by Shweta597** [comment]
@adityabisoi  please assign this issue to me

**Comment by SonakshiGoyal** [comment]
@adityabisoi can you please assign this to me

**Comment by adityabisoi** [comment]
A PR has already been made for this issue. Please select any other issue.
