### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/notation-converter#28]
## 🚀 Feature

The current version of the homepage is too plain and simple. Please create a wireframe for a better-looking UI using a wireframing tool, and implement it.

**Note:** The project uses ReactJS for its UI.

**Comment by artimanputra** [comment]
Can I work On this issue? Could you please assign it to me?

**Comment by artimanputra** [comment]
@adityabisoi can I work on this issue under gssoc'22?

**Comment by RiyaBhandari-2811** [comment]
I know it's been covered but it's not at all user friendly .

1. No Active link css .
2. Not a stand out Logo.
3. No Title to your website .
4. No favicon .

As per I know these are the small things that make websites stand out . and if these things are not followed User will definitely loose interest and maybe not revisit the website .

**Comment by adityabisoi** [comment]
@artimanputra @RiyaBhandari-2811 You both can work on this together.

**Comment by RiyaBhandari-2811** [comment]
I'm not able to find the nav-link className only . I've done some of my
work only active link is remaining . Would you pls help me with that ??
There are no comments also that's why I'm confused .

**Comment by RiyaBhandari-2811** [comment]
Hello @adityabisoi  I've solve these issue . Will you pls Review it and lemme know your thoughts regarding same . If all is ok pls merge mine pull request and close this issue plss .
