### ISSUE TITLE
Add issue template: feature request

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/notation-converter#3]
Add an issue template for requesting new features in the project.

**Comment by kunaljain0212** [comment]
Can I work on this, please? @adityabisoi

**Comment by adityabisoi** [comment]
@kunaljain0212 One issue at a time, mate:)

**Comment by iamrajiv** [comment]
@adityabisoi I want to work on this.

**Comment by adityabisoi** [comment]
@iamrajiv Sure.
