### ISSUE TITLE
Provide color gradient

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/notation-converter#30]
Provide come nice color gradients to the mentors to choose for the project. The color gradient selected will be implemented across all pages.

**Comment by Aniket-508** [comment]
These are some of the gradients @adityabisoi .

![g3](https://user-images.githubusercontent.com/71957423/145348895-b024e02d-f737-491c-9dec-936dc57e4aac.JPG)
![g4](https://user-images.githubusercontent.com/71957423/145348899-eca418f2-f0e3-4c85-8570-eac73495f795.JPG)
![g1](https://user-images.githubusercontent.com/71957423/145348879-306dd1c0-fb4d-4310-8da7-12676cb13977.JPG)
![g2](https://user-images.githubusercontent.com/71957423/145348889-1957080d-203f-4ac6-8633-0cc31173001b.JPG)

**Comment by adityabisoi** [comment]
@Aniket-508 The 3rd one seems to be nice.

**Comment by Aniket-508** [comment]
How should I proceed forward then or is this issue solved? @adityabisoi

**Comment by adityabisoi** [comment]
@Aniket-508 Please apply the mentioned color gradient on the project's navbar & footer, and make a PR

**Comment by Aniket-508** [comment]
There is no footer actually! @adityabisoi

**Comment by Aniket-508** [comment]
![Screenshot (149)](https://user-images.githubusercontent.com/71957423/145709836-ac20044f-60ea-465c-b7b0-5e2d5be11b21.png)

The color on hover is the same as submit button. Does this look good? @adityabisoi

**Comment by adityabisoi** [comment]
@Aniket-508 Yes, it does. Did you apply this to the footer as well?

**Comment by Aniket-508** [comment]
Yep, sending PR!
