### ISSUE TITLE
Provide a logo to the project

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/notation-converter#33]
Provide a logo which should be in close association with the idea of the projct.

**Comment by AyushK-101** [comment]
[Notation Converter-logos.zip](https://github.com/adityabisoi/notation-converter/files/7679238/Notation.Converter-logos.zip)

I would like to work on this. How's this?

**Comment by AyushK-101** [comment]
![Notation](https://user-images.githubusercontent.com/86164395/145294170-c76804c3-6804-41a9-9c41-decbb54d0cfa.PNG)

**Comment by adityabisoi** [comment]
Looks Good to me. Any more ideas?

**Comment by AyushK-101** [comment]
![Notationidea3](https://user-images.githubusercontent.com/86164395/145391820-21cc0c96-b42e-47bd-aacc-f9b93ca2792c.PNG)

Sticking to the stack image which represents the stack method of notation conversion.

**Comment by adityabisoi** [comment]
The first one looks better. You can create a PR adding the logo at the top of README.

**Comment by subhangi2731** [comment]
@AyushK-101 The first one looks good please send a pr for this

**Comment by AyushK-101** [comment]
Ok, I have sent a PR

**Comment by AyushK-101** [comment]
Made a new PR, have a look.
