### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/notation-converter#4]
Add a pull request template to the project.

**Comment by subhangi2731** [comment]
Please assign this issue to me? @adityabisoi

**Comment by adityabisoi** [comment]
@subhangi2731 Go ahead

**Comment by luckykumarirai** [comment]
Hello, @adityabisoi I have sent a PR regarding this issue because I have observed that nobody makes a PR for this for 24 days.
