### ISSUE TITLE
Beautifying README.md with emojis

### ISSUE THREAD

**Issue by mandiraghosh783** [adityabisoi/notation-converter#48]
Can I add few emojis to README.md so that it looks more beautiful?

**Comment by adityabisoi** [comment]
Sure!

**Comment by Aayush987** [comment]
@adityabisoi Can i work on this issue?

**Comment by Aayush987** [comment]
@adityabisoi  I think this issue was already resolved but this issue was not closed as the readme already contains lots of emojis. Should I still work on it?

**Comment by adityabisoi** [comment]
@Aayush987 You can create a PR for moving the `open source events` to the end of readme, after contributors list.

**Comment by Aayush987** [comment]
> @Aayush987 You can create a PR for moving the `open source events` to the end of readme, after contributors list.

Ok, thank you
