### ISSUE TITLE
Improve form UI

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/notation-converter#5]
Improve the UI of the form, probably use a framework such as Ant design, Sematic UI, or Material UI

**Comment by codewithvk** [comment]
Can you assign me, I Would like to happy to fix this issue.

**Comment by adityabisoi** [comment]
Are you a KWOC participant?

**Comment by codewithvk** [comment]
@adityabisoi  Yes

**Comment by adityabisoi** [comment]
@codewithvk Go ahead. Be sure to share your designs in the Gitter channel before working on them.

**Comment by codewithvk** [comment]
Sure. I will be working on  6 Desc on words.

**Comment by luckykumarirai** [comment]
Hello,
I would like to contribute to the issue(Improve the UI of the form, probably use a framework such as Ant design, Sematic UI, or Material UI).

**Comment by adityabisoi** [comment]
@luckykumarirai Go ahead
