### ISSUE TITLE
Add a dark-light theme toggle button

### ISSUE THREAD

**Issue by kunalkatara12** [adityabisoi/notation-converter#51]
Can I add a dark-light theme toggle button if you want ?
Can you add a GSSoC 22 label?

**Comment by Abhilasha-Jairath** [comment]
https://github.com/Lakhankumawat/LearnCPP

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by adityabisoi** [comment]
@Abhilasha-Jairath Issue is already taken. Please create a new one.

**Comment by kunalkatara12** [comment]
I have added Dark light theme toggle switch. Will you please review it .

**Comment by kunalkatara12** [comment]
Sir can you change the label to 'GSSoC22' and 'Level-2' because this are the correct labels so that score will be given to me.
