### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by Nitya-S27** [adityabisoi/notation-converter#52]
## 🚀 Feature

(The app should be in dark theme)

## Please Describe The Problem To Be Solved

(The functionality is perfect but it's UI is not appealing to the end user)

## (Optional): Suggest a Solution

(Using a good dark color palette)

**Comment by Nitya-S27** [comment]
@adityabisoi please assign this to me 
Thanks and Regards.

**Comment by adityabisoi** [comment]
Already covered in #28 . Please create issues which are not already covered/ comment on existing ones.

**Comment by adityabisoi** [comment]
You can comment on issue #28 , and you will be assigned if the current assignee doesn't complete the task on time.
