### ISSUE TITLE
Make UI User friendly

### ISSUE THREAD

**Issue by RiyaBhandari-2811** [adityabisoi/notation-converter#53]
## Please Describe The Problem To Be Solved

While i was interact with notation-converter i found that the nav bar isn't that user friendly .

##  Suggest a Solution

Things to address include:
-  Make logo stand out .
- Work on active links so that user know in which section they are .
- Remove the title ReactApp -> Notation-converter .
- add favicon for better branding .

## What happens if you skip this Issue ?
- User will loose interest and maybe not revisit the website .

## Tech Stack 
- [x]  HTML
- [x] CSS
- [x] ReactJs

> **Note** :  As a GSSOC-Contributor'22 I would like to contribute through these issue if you give me the opportunity . If yes pls do comment so I can start working accordingly . Thank you :)

**Comment by adityabisoi** [comment]
Already covered in #28 . Please create issues which are not already covered/ comment on existing ones.

**Comment by adityabisoi** [comment]
You can comment on issue #28 , and you will be assigned if the current assignee doesn't complete the task on time.

**Comment by RiyaBhandari-2811** [comment]
> You can comment on issue #28 , and you will be assigned if the current assignee doesn't complete the task on time.

I know it's been covered but it's not at all user friendly .

1. No Active link css .
2. Not a stand out Logo.
3. No Title to your website .
4. No favicon .

As per I know these are the small things that make websites stand out . and if these things are not followed User will definitely  loose interest and maybe not revisit the website .

**Comment by RiyaBhandari-2811** [comment]
> You can comment on issue #28 , and you will be assigned if the current assignee doesn't complete the task on time.

I know it's been covered but it's not at all user friendly .

1. No Active link css .
2. Not a stand out Logo.
3. No Title to your website .
4. No favicon .

As per I know these are the small things that make websites stand out . and if these things are not followed User will definitely loose interest and maybe not revisit the website .
