### ISSUE TITLE
Code in different languages.

### ISSUE THREAD

**Issue by ranimanya** [adityabisoi/notation-converter#55]
## 🚀 Feature

Students generally start learning data structures in C/C++ language.  Python is also a popular language among students. The idea here is that we can present code in several languages which provide an option for students to choose which language they want to learn. 

Here I would like to contribute code in C, C++ and python language for all conversions. 

I'm a Gssoc'22 participant, please assign this issue to me :-)

**Comment by adityabisoi** [comment]
@ranimanya Good idea. You can create a new folder with sub-folders for different languages.

**Comment by ranimanya** [comment]
@adityabisoi  why you did not merge my pr?....instead you added all the files......?
