### ISSUE TITLE
Add infix to prefix conversion

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/notation-converter#6]
Write a function to convert infix to prefix notation

**Comment by subhangi2731** [comment]
can I please work on this? @adityabisoi

**Comment by adityabisoi** [comment]
@subhangi2731 One issue at a time

**Comment by munditva** [comment]
I would like to work on this issue.
One question all code is to be in JS?

**Comment by adityabisoi** [comment]
@munditva Go ahead. Yes, it should be in JS. You can see the tech stack from the documentation.

**Comment by munditva** [comment]
@adityabisoi I have opened a PR related to this. Please check
